addons:
    apt:
        packages:
            - build-essential
            - cmake
            - cpanminus
            - fortune-mod
            - hunspell
            - libdb5.3-dev
            - libgd-dev
            - libhunspell-dev
            - libncurses-dev
            - libpcre3-dev
            - libperl-dev
            - lynx
            - myspell-en-gb
            - perl
            - python3
            - python3-pip
            - python3-setuptools
            - valgrind
            - xsltproc
            - xz-utils
            - zip
cache:
    ccache: true
    directories:
        - $HOME/perl_modules
os: linux
dist: xenial
install:
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
    - cpanm --notest Bit::Vector Carp::Always Class::XSAccessor File::Which GD Getopt::Long IO::All Image::Size Path::Tiny Perl::Critic Perl::Tidy Test::Code::TidyAll Term::ReadKey
language: perl
python:
    - "3.5"
script:
    - mkdir build
    - cd build
    - WML_TEST_BUILD=1 WML_TEST_TIDY=1 perl ../src/wml_test/run_test.pl
