jobs:
    test-fc-solve:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
            with:
                submodules: 'true'
        -   run: sudo apt-get update -qq
        -   run: sudo apt-get --no-install-recommends install -y eatmydata
        -   run: sudo eatmydata apt-get --no-install-recommends install -y build-essential
                cmake cpanminus hunspell hunspell-en-gb libdb5.3-dev libgd-dev libhunspell-dev
                libncurses-dev libpcre3-dev libperl-dev lynx perl txt2html xz-utils
                zip
        -   run: local_lib_shim() { eval "$(perl -Mlocal::lib=$HOME/perl_modules)";
                } ; local_lib_shim ; cpanm local::lib
        -   run: local_lib_shim() { eval "$(perl -Mlocal::lib=$HOME/perl_modules)";
                } ; local_lib_shim ; eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
        -   run: local_lib_shim() { eval "$(perl -Mlocal::lib=$HOME/perl_modules)";
                } ; local_lib_shim ; cpanm --notest Net::SSLeay
        -   run: local_lib_shim() { eval "$(perl -Mlocal::lib=$HOME/perl_modules)";
                } ; local_lib_shim ; cpanm --notest Bit::Vector Carp::Always Class::XSAccessor
                Code::TidyAll::Plugin::TestCount File::Which GD Getopt::Long HTML::TextToHTML
                Image::Size Path::Tiny Perl::Critic Perl::Tidy Term::ReadKey Test::Code::TidyAll
        -   run: local_lib_shim() { eval "$(perl -Mlocal::lib=$HOME/perl_modules)";
                } ; local_lib_shim ; mkdir build
        -   run: local_lib_shim() { eval "$(perl -Mlocal::lib=$HOME/perl_modules)";
                } ; local_lib_shim ; cd build
        -   run: local_lib_shim() { eval "$(perl -Mlocal::lib=$HOME/perl_modules)";
                } ; local_lib_shim ; WML_TEST_BUILD=1 WML_TEST_TIDY=1 TIDYALL_DATA_DIR=$HOME/tidyall.d
                perl ../src/wml_test/run_test.pl
name: use-github-actions
'on':
- push
